---
common: &common
  adapter: postgresql
  host: postgres
  password: postgres
  user: postgres

development:
  <<: *common
  database: development

test:
  <<: *common
  database: test

production:
  <<: *common
  database: development

