# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

---
shared:
  admin_mailer:
    to: recipient@example.com
  smtp:
    user_name: someuser@example.com
    password: somepassword
    from: no-reply-user_admin@example.com

# Environmental secrets are only available for that specific environment.

development:
  # yamllint disable-line rule:line-length
  secret_key_base: 716f7c943272b9631f2b1358e3f171f8d05fe3219d56030cde7a3979c8518719a57f32e891a81bc556a49f95e8728deb3df3f48251f49c84653dc2bcca64f992

test:
  # yamllint disable-line rule:line-length
  secret_key_base: a44e9a54612ae0ce497017b317f1346d68e90baf39d07f951179e0b19c54a08f1643e216b474a887b02f9346137bbaccff41339f4954f5defdf3253dc1b194f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
